/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Config */
    get: operations["config_api_v1_config_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/event-series": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Series */
    get: operations["list_series_api_v1_event_series_get"];
    put?: never;
    /** Create Series */
    post: operations["create_series_api_v1_event_series_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/event-series/{series_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Series */
    put: operations["update_series_api_v1_event_series__series_id__put"];
    post?: never;
    /** Delete Series */
    delete: operations["delete_series_api_v1_event_series__series_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/event-series/{series_id}/exceptions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Save Exception */
    post: operations["save_exception_api_v1_event_series__series_id__exceptions_post"];
    /** Remove Exception */
    delete: operations["remove_exception_api_v1_event_series__series_id__exceptions_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Events */
    get: operations["list_events_api_v1_events_get"];
    put?: never;
    /** Add Event */
    post: operations["add_event_api_v1_events_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/events/{event_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Event */
    put: operations["update_event_api_v1_events__event_id__put"];
    post?: never;
    /** Delete Event */
    delete: operations["delete_event_api_v1_events__event_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/family-events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Events */
    get: operations["events_api_v1_family_events_get"];
    put?: never;
    /** Add Event */
    post: operations["add_event_api_v1_family_events_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/family-events/{event_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Event */
    put: operations["update_event_api_v1_family_events__event_id__put"];
    post?: never;
    /** Remove Event */
    delete: operations["remove_event_api_v1_family_events__event_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/icons": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Icons */
    get: operations["icons_api_v1_icons_get"];
    put?: never;
    /** Add Icon */
    post: operations["add_icon_api_v1_icons_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Members */
    get: operations["list_members_api_v1_members_get"];
    put?: never;
    /** Add Member */
    post: operations["add_member_api_v1_members_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/members/{member_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Member */
    put: operations["update_member_api_v1_members__member_id__put"];
    post?: never;
    /** Archive Member */
    delete: operations["archive_member_api_v1_members__member_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/members/{member_id}/restore": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restore Member */
    post: operations["restore_member_api_v1_members__member_id__restore_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/notices": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Notices */
    get: operations["notices_api_v1_notices_get"];
    put?: never;
    /** Create Notice */
    post: operations["create_notice_api_v1_notices_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/notices/{notice_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Notice */
    put: operations["update_notice_api_v1_notices__notice_id__put"];
    post?: never;
    /** Delete Notice */
    delete: operations["delete_notice_api_v1_notices__notice_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/task-occurrences": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Occurrences */
    get: operations["occurrences_api_v1_task_occurrences_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Tasks */
    get: operations["tasks_api_v1_tasks_get"];
    put?: never;
    /** Create Task */
    post: operations["create_task_api_v1_tasks_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks/{task_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Task */
    put: operations["update_task_api_v1_tasks__task_id__put"];
    post?: never;
    /** Archive Task */
    delete: operations["archive_task_api_v1_tasks__task_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks/{task_id}/completion": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Complete Task */
    put: operations["complete_task_api_v1_tasks__task_id__completion_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * Category
     * @enum {string}
     */
    Category: "school" | "activities" | "medical" | "friends" | "other";
    /** CompletionInput */
    CompletionInput: {
      /** Completed */
      completed: boolean;
      /**
       * Day
       * Format: date
       */
      day: string;
      /**
       * Member Id
       * Format: uuid
       */
      member_id: string;
    };
    /**
     * EndMode
     * @enum {string}
     */
    EndMode: "never" | "date" | "count";
    /** EventInput */
    EventInput: {
      /** @default other */
      category: components["schemas"]["Category"];
      /** Custom Icon Id */
      custom_icon_id?: string | null;
      /**
       * Ends At
       * Format: date-time
       */
      ends_at: string;
      /**
       * Member Id
       * Format: uuid
       */
      member_id: string;
      /**
       * Starts At
       * Format: date-time
       */
      starts_at: string;
      /** Title */
      title: string;
    };
    /** EventOutput */
    EventOutput: {
      /** @default other */
      category: components["schemas"]["Category"];
      /** Custom Icon Id */
      custom_icon_id?: string | null;
      /**
       * Ends At
       * Format: date-time
       */
      ends_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Member Id
       * Format: uuid
       */
      member_id: string;
      /** Occurrence Date */
      occurrence_date?: string | null;
      /** Occurrence Time */
      occurrence_time?: string | null;
      /** Recurring Series Id */
      recurring_series_id?: string | null;
      /**
       * Starts At
       * Format: date-time
       */
      starts_at: string;
      /** Title */
      title: string;
    };
    /** EventUpdate */
    EventUpdate: {
      category?: components["schemas"]["Category"] | null;
      /** Custom Icon Id */
      custom_icon_id?: string | null;
      /**
       * Ends At
       * Format: date-time
       */
      ends_at: string;
      /**
       * Starts At
       * Format: date-time
       */
      starts_at: string;
      /** Title */
      title: string;
    };
    /** ExceptionInput */
    ExceptionInput: {
      /**
       * Cancelled
       * @default false
       */
      cancelled: boolean;
      /**
       * Has Icon Override
       * @default false
       */
      has_icon_override: boolean;
      /**
       * Occurrence Date
       * Format: date
       */
      occurrence_date: string;
      /**
       * Occurrence Time
       * Format: time
       */
      occurrence_time: string;
      override_category?: components["schemas"]["Category"] | null;
      /** Override Custom Icon Id */
      override_custom_icon_id?: string | null;
      /** Override Duration Minutes */
      override_duration_minutes?: number | null;
      /** Override Start Time */
      override_start_time?: string | null;
      /** Override Title */
      override_title?: string | null;
    };
    /** ExceptionOutput */
    ExceptionOutput: {
      /**
       * Cancelled
       * @default false
       */
      cancelled: boolean;
      /**
       * Has Icon Override
       * @default false
       */
      has_icon_override: boolean;
      /**
       * Occurrence Date
       * Format: date
       */
      occurrence_date: string;
      /**
       * Occurrence Time
       * Format: time
       */
      occurrence_time: string;
      override_category?: components["schemas"]["Category"] | null;
      /** Override Custom Icon Id */
      override_custom_icon_id?: string | null;
      /** Override Duration Minutes */
      override_duration_minutes?: number | null;
      /** Override Start Time */
      override_start_time?: string | null;
      /** Override Title */
      override_title?: string | null;
      /**
       * Series Id
       * Format: uuid
       */
      series_id: string;
    };
    /** FamilyEventInput */
    FamilyEventInput: {
      /** Custom Icon Id */
      custom_icon_id?: string | null;
      /**
       * Day
       * Format: date
       */
      day: string;
      /** @default birthday */
      icon: components["schemas"]["FamilyIcon"];
      /** Title */
      title: string;
    };
    /** FamilyEventOutput */
    FamilyEventOutput: {
      /** Custom Icon Id */
      custom_icon_id?: string | null;
      /**
       * Day
       * Format: date
       */
      day: string;
      /** @default birthday */
      icon: components["schemas"]["FamilyIcon"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Title */
      title: string;
    };
    /**
     * FamilyIcon
     * @enum {string}
     */
    FamilyIcon: "birthday" | "celebration" | "trip" | "other";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** IconInput */
    IconInput: {
      /** Image Data */
      image_data: string;
      /** Name */
      name: string;
    };
    /** IconOutput */
    IconOutput: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Data */
      image_data: string;
      /** Name */
      name: string;
    };
    /** MemberInput */
    MemberInput: {
      /** Color */
      color: string;
      /** Name */
      name: string;
    };
    /** MemberOutput */
    MemberOutput: {
      /**
       * Active
       * @default true
       */
      active: boolean;
      /** Color */
      color: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Photo Data */
      photo_data?: string | null;
    };
    /** MemberUpdate */
    MemberUpdate: {
      /** Name */
      name: string;
      /** Photo Data */
      photo_data?: string | null;
    };
    /**
     * NoticeIcon
     * @enum {string}
     */
    NoticeIcon: "uniform" | "tracksuit" | "trip" | "other";
    /** NoticeInput */
    NoticeInput: {
      /** Custom Icon Id */
      custom_icon_id?: string | null;
      /**
       * Day
       * Format: date
       */
      day: string;
      /** @default other */
      icon: components["schemas"]["NoticeIcon"];
      /**
       * Member Id
       * Format: uuid
       */
      member_id: string;
      /** Title */
      title: string;
    };
    /** NoticeOutput */
    NoticeOutput: {
      /** Custom Icon Id */
      custom_icon_id?: string | null;
      /**
       * Day
       * Format: date
       */
      day: string;
      /** @default other */
      icon: components["schemas"]["NoticeIcon"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Member Id
       * Format: uuid
       */
      member_id: string;
      /** Title */
      title: string;
    };
    /** NoticeUpdate */
    NoticeUpdate: {
      /** Custom Icon Id */
      custom_icon_id?: string | null;
      /**
       * Day
       * Format: date
       */
      day: string;
      /** @default other */
      icon: components["schemas"]["NoticeIcon"];
      /** Title */
      title: string;
    };
    /** OccurrenceOutput */
    OccurrenceOutput: {
      /** Completed */
      completed: boolean;
      /** Custom Icon Id */
      custom_icon_id?: string | null;
      /**
       * Day
       * Format: date
       */
      day: string;
      icon: components["schemas"]["TaskIcon"];
      /**
       * Member Id
       * Format: uuid
       */
      member_id: string;
      /**
       * Task Id
       * Format: uuid
       */
      task_id: string;
      /** Title */
      title: string;
    };
    /** SeriesInput */
    SeriesInput: {
      /** @default other */
      category: components["schemas"]["Category"];
      /** Custom Icon Id */
      custom_icon_id?: string | null;
      /** Duration Minutes */
      duration_minutes: number;
      /** End Date */
      end_date?: string | null;
      /** @default never */
      end_mode: components["schemas"]["EndMode"];
      frequency: components["schemas"]["app__domain__recurrence__Frequency"];
      /** Interval */
      interval: number;
      /**
       * Member Id
       * Format: uuid
       */
      member_id: string;
      /** Occurrence Count */
      occurrence_count?: number | null;
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
      /**
       * Start Time
       * Format: time
       */
      start_time: string;
      /** Timezone */
      timezone: string;
      /** Title */
      title: string;
      /** Weekdays */
      weekdays?: number[];
    };
    /** SeriesOutput */
    SeriesOutput: {
      /** @default other */
      category: components["schemas"]["Category"];
      /** Custom Icon Id */
      custom_icon_id?: string | null;
      /** Duration Minutes */
      duration_minutes: number;
      /** End Date */
      end_date?: string | null;
      /** @default never */
      end_mode: components["schemas"]["EndMode"];
      frequency: components["schemas"]["app__domain__recurrence__Frequency"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Interval */
      interval: number;
      /**
       * Member Id
       * Format: uuid
       */
      member_id: string;
      /** Occurrence Count */
      occurrence_count?: number | null;
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
      /**
       * Start Time
       * Format: time
       */
      start_time: string;
      /** Timezone */
      timezone: string;
      /** Title */
      title: string;
      /** Weekdays */
      weekdays?: number[];
    };
    /**
     * TaskIcon
     * @enum {string}
     */
    TaskIcon: "tooth" | "backpack" | "bed" | "other";
    /** TaskInput */
    TaskInput: {
      /** Custom Icon Id */
      custom_icon_id?: string | null;
      /** @default daily */
      frequency: components["schemas"]["app__domain__daily__Frequency"];
      /** @default other */
      icon: components["schemas"]["TaskIcon"];
      /** Member Ids */
      member_ids: string[];
      /**
       * Starts On
       * Format: date
       */
      starts_on: string;
      /** Title */
      title: string;
    };
    /** TaskOutput */
    TaskOutput: {
      /** Active */
      active: boolean;
      /** Custom Icon Id */
      custom_icon_id?: string | null;
      /** @default daily */
      frequency: components["schemas"]["app__domain__daily__Frequency"];
      /** @default other */
      icon: components["schemas"]["TaskIcon"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Member Ids */
      member_ids: string[];
      /**
       * Starts On
       * Format: date
       */
      starts_on: string;
      /** Title */
      title: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /**
     * Frequency
     * @enum {string}
     */
    app__domain__daily__Frequency: "daily" | "once";
    /**
     * Frequency
     * @enum {string}
     */
    app__domain__recurrence__Frequency: "daily" | "weekly" | "monthly";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  config_api_v1_config_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  list_series_api_v1_event_series_get: {
    parameters: {
      query?: {
        member_id?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SeriesOutput"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_series_api_v1_event_series_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SeriesInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SeriesOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_series_api_v1_event_series__series_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        series_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SeriesInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SeriesOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_series_api_v1_event_series__series_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        series_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  save_exception_api_v1_event_series__series_id__exceptions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        series_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExceptionInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExceptionOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_exception_api_v1_event_series__series_id__exceptions_delete: {
    parameters: {
      query: {
        occurrence_date: string;
        occurrence_time: string;
      };
      header?: never;
      path: {
        series_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_events_api_v1_events_get: {
    parameters: {
      query: {
        start: string;
        end: string;
        member_id?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventOutput"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_event_api_v1_events_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EventInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_event_api_v1_events__event_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        event_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EventUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_event_api_v1_events__event_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        event_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  events_api_v1_family_events_get: {
    parameters: {
      query: {
        start: string;
        end: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FamilyEventOutput"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_event_api_v1_family_events_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FamilyEventInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FamilyEventOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_event_api_v1_family_events__event_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        event_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FamilyEventInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FamilyEventOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_event_api_v1_family_events__event_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        event_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  icons_api_v1_icons_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IconOutput"][];
        };
      };
    };
  };
  add_icon_api_v1_icons_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["IconInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IconOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_members_api_v1_members_get: {
    parameters: {
      query?: {
        include_archived?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberOutput"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_member_api_v1_members_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MemberInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_member_api_v1_members__member_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        member_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MemberUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  archive_member_api_v1_members__member_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        member_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  restore_member_api_v1_members__member_id__restore_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        member_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  notices_api_v1_notices_get: {
    parameters: {
      query: {
        day: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NoticeOutput"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_notice_api_v1_notices_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NoticeInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NoticeOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_notice_api_v1_notices__notice_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        notice_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NoticeUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NoticeOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_notice_api_v1_notices__notice_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        notice_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  occurrences_api_v1_task_occurrences_get: {
    parameters: {
      query: {
        day: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OccurrenceOutput"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  tasks_api_v1_tasks_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskOutput"][];
        };
      };
    };
  };
  create_task_api_v1_tasks_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_task_api_v1_tasks__task_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  archive_task_api_v1_tasks__task_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  complete_task_api_v1_tasks__task_id__completion_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompletionInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OccurrenceOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
